### PR TITLE
New heap library

### PR DESCRIPTION
**Pull request by slondr**
Replaced the current (questionably licensed) heap library with a public domain one sourced from https://luapower.com/. Adjusted ai.lua to properly use the new library.

### CODE REVIEW

**Comment by stephoro** [comment]
In battles, this PR causes enemies to flee from the player, rather than move towards them.

**Comment by stephoro** [comment]
also add the license of this library to the resources/licenses folder

**Comment by stephoro** [comment]
also add yerself to the copyright statement at the topic of the LICENSE file

**Comment by slondr** [comment]
Should be all good now.

**Comment by stephoro** [comment]
confirmed, gg

**Pull request merged**
